import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import type { AuthProvider, ExtractedIdentity } from "../base.js";
import { EasyAuthError } from "../../core/errors.js";

export interface TotpCredentials {
  /**
   * Account identifier (e.g. email, username, or user ID)
   */
  account: string;

  /**
   * 6-digit dynamic code generated by Google Authenticator / TOTP app
   */
  code: string;

  /**
   * The Base32 shared secret key.
   * NOTE: For security, client-supplied secrets are ignored during authentication
   * unless `allowClientSecret: true` is explicitly configured on TotpProvider.
   */
  secret?: string;
}

export interface TotpProfile {
  account: string;
}

export interface TotpProviderOptions {
  /**
   * Provider name. Defaults to "totp".
   */
  name?: string;

  /**
   * Time step in seconds. Defaults to 30.
   */
  step?: number;

  /**
   * Drift window (number of steps before and after allowed). Defaults to 1 (+/- 30 seconds).
   */
  window?: number;

  /**
   * Number of digits. Defaults to 6.
   */
  digits?: number;

  /**
   * Authoritative server-side shared secret or secret resolver function.
   * In production, this should always be provided.
   */
  secret?: string | ((account: string) => Promise<string | null | undefined> | string | null | undefined);

  /**
   * Allow client-supplied secrets in credentials payload.
   * WARNING: For security, this defaults to false.
   * Only enable for testing or stateless flows where clients hold secrets.
   */
  allowClientSecret?: boolean;

  /**
   * Automatically track and enforce monotonic time-steps per account to prevent code reuse within the window.
   * Defaults to true (RFC 6238 Section 5.2 compliance).
   */
  enforceMonotonicCounter?: boolean;

  /**
   * Optional custom hook to validate and consume OTP (e.g. against a distributed Redis cache).
   */
  consumeOtp?: (account: string, code: string, counter: number) => Promise<boolean> | boolean;

  /**
   * Maximum failed verification attempts before temporary lockout. Defaults to 5.
   * Set to 0 to disable.
   */
  maxFailedAttempts?: number;

  /**
   * Lockout duration in milliseconds after exceeding maxFailedAttempts. Defaults to 60000 (1 minute).
   */
  lockoutDurationMs?: number;
}

const BASE32_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";

/**
 * Base32 decode utility (RFC 4648)
 */
export function base32Decode(base32: string): Buffer {
  const clean = base32.toUpperCase().replace(/=+$/, "").replace(/\s+/g, "");
  let bits = 0;
  let value = 0;
  const output: number[] = [];

  for (let i = 0; i < clean.length; i++) {
    const idx = BASE32_ALPHABET.indexOf(clean[i]);
    if (idx === -1) {
      throw new Error(`Invalid Base32 character: "${clean[i]}"`);
    }
    value = (value << 5) | idx;
    bits += 5;

    if (bits >= 8) {
      output.push((value >>> (bits - 8)) & 255);
      bits -= 8;
    }
  }

  return Buffer.from(output);
}

/**
 * Base32 encode utility (RFC 4648)
 */
export function base32Encode(buffer: Buffer): string {
  let bits = 0;
  let value = 0;
  let output = "";

  for (let i = 0; i < buffer.length; i++) {
    value = (value << 8) | buffer[i];
    bits += 8;

    while (bits >= 5) {
      output += BASE32_ALPHABET[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }

  if (bits > 0) {
    output += BASE32_ALPHABET[(value << (5 - bits)) & 31];
  }

  return output;
}

/**
 * TotpProvider (Google Authenticator / RFC 6238 TOTP).
 *
 * Treats 6-digit TOTP verification purely as a standard authentication provider.
 * Zero external dependencies, timing-safe verification, Google Authenticator compatible.
 */
export class TotpProvider implements AuthProvider<TotpCredentials, TotpProfile> {
  readonly name: string;
  readonly type = "totp";
  private readonly step: number;
  private readonly window: number;
  private readonly digits: number;
  private readonly options: TotpProviderOptions;

  private readonly lastUsedTimeSteps = new Map<string, number>();
  private readonly failedAttempts = new Map<string, { count: number; lockedUntil: number }>();

  constructor(options?: TotpProviderOptions) {
    this.name = (options?.name || "totp").toLowerCase();
    this.step = options?.step ?? 30;
    this.window = options?.window ?? 1;
    this.digits = options?.digits ?? 6;
    this.options = options || {};
  }

  /**
   * Generates a new random Base32 secret key compatible with Google Authenticator
   */
  static generateSecret(length = 20): string {
    const bytes = randomBytes(length);
    return base32Encode(bytes);
  }

  /**
   * Generates an otpauth:// URI suitable for creating QR codes for Google Authenticator
   */
  static generateTotpUri(params: {
    secret: string;
    accountName: string;
    issuer?: string;
    digits?: number;
    period?: number;
  }): string {
    const { secret, accountName, issuer, digits = 6, period = 30 } = params;
    const label = issuer
      ? `${encodeURIComponent(issuer)}:${encodeURIComponent(accountName)}`
      : encodeURIComponent(accountName);

    let uri = `otpauth://totp/${label}?secret=${secret}&digits=${digits}&period=${period}`;
    if (issuer) {
      uri += `&issuer=${encodeURIComponent(issuer)}`;
    }
    return uri;
  }

  /**
   * Generates a dynamic token for the given secret and timestamp
   */
  static generateToken(
    secret: string,
    options?: { timestamp?: number; step?: number; digits?: number }
  ): string {
    const timestamp = options?.timestamp ?? Date.now();
    const step = options?.step ?? 30;
    const digits = options?.digits ?? 6;

    const secretBuffer = base32Decode(secret);
    const counter = Math.floor(timestamp / 1000 / step);

    const buf = Buffer.alloc(8);
    buf.writeBigInt64BE(BigInt(counter));

    const hmac = createHmac("sha1", secretBuffer).update(buf).digest();
    const offset = hmac[hmac.length - 1] & 0x0f;
    const binary =
      ((hmac[offset] & 0x7f) << 24) |
      ((hmac[offset + 1] & 0xff) << 16) |
      ((hmac[offset + 2] & 0xff) << 8) |
      (hmac[offset + 3] & 0xff);

    const otp = (binary % 10 ** digits).toString().padStart(digits, "0");
    return otp;
  }

  /**
   * Verifies a TOTP token against a secret with timing-safe comparison and window drift tolerance.
   * Returns validation status along with matched time-step counter.
   */
  static verifyTokenWithCounter(
    secret: string,
    token: string,
    options?: { timestamp?: number; step?: number; window?: number; digits?: number }
  ): { valid: boolean; counter?: number } {
    const timestamp = options?.timestamp ?? Date.now();
    const step = options?.step ?? 30;
    const window = options?.window ?? 1;
    const digits = options?.digits ?? 6;

    if (!token || typeof token !== "string" || token.length !== digits || !/^\d+$/.test(token)) {
      return { valid: false };
    }

    let secretBuffer: Buffer;
    try {
      secretBuffer = base32Decode(secret);
    } catch {
      return { valid: false };
    }

    const currentCounter = Math.floor(timestamp / 1000 / step);

    for (let i = -window; i <= window; i++) {
      const counter = currentCounter + i;
      const buf = Buffer.alloc(8);
      buf.writeBigInt64BE(BigInt(counter));

      const hmac = createHmac("sha1", secretBuffer).update(buf).digest();
      const offset = hmac[hmac.length - 1] & 0x0f;
      const binary =
        ((hmac[offset] & 0x7f) << 24) |
        ((hmac[offset + 1] & 0xff) << 16) |
        ((hmac[offset + 2] & 0xff) << 8) |
        (hmac[offset + 3] & 0xff);

      const expected = (binary % 10 ** digits).toString().padStart(digits, "0");

      if (timingSafeEqual(Buffer.from(expected), Buffer.from(token))) {
        return { valid: true, counter };
      }
    }

    return { valid: false };
  }

  /**
   * Verifies a TOTP token against a secret with timing-safe comparison and window drift tolerance.
   */
  static verifyToken(
    secret: string,
    token: string,
    options?: { timestamp?: number; step?: number; window?: number; digits?: number }
  ): boolean {
    return TotpProvider.verifyTokenWithCounter(secret, token, options).valid;
  }

  /**
   * Standard AuthProvider verifyAndExtract implementation
   */
  async verifyAndExtract(credentials: TotpCredentials): Promise<ExtractedIdentity<TotpProfile>> {
    if (!credentials) {
      throw new EasyAuthError("INVALID_CREDENTIALS", "TOTP credentials are required.");
    }

    const { account, code } = credentials;

    if (!account || typeof account !== "string" || account.trim().length === 0) {
      throw new EasyAuthError("INVALID_CREDENTIALS", "Account identifier is required for TOTP verification.");
    }

    const normalizedAccount = account.trim().toLowerCase();
    const maxFailed = this.options.maxFailedAttempts ?? 5;
    const lockoutMs = this.options.lockoutDurationMs ?? 60000;

    // 🔒 Brute-force rate limiting: Reject if account is currently locked out
    if (maxFailed > 0) {
      const lock = this.failedAttempts.get(normalizedAccount);
      if (lock && Date.now() < lock.lockedUntil) {
        const remainingSec = Math.ceil((lock.lockedUntil - Date.now()) / 1000);
        throw new EasyAuthError(
          "RATE_LIMIT_EXCEEDED",
          `Too many failed TOTP verification attempts for account "${account}". Please retry after ${remainingSec}s.`
        );
      }
    }

    if (!code || typeof code !== "string" || code.trim().length !== this.digits) {
      throw new EasyAuthError(
        "INVALID_CREDENTIALS",
        `TOTP code must be a ${this.digits}-digit string.`
      );
    }

    // 🔒 Security: Resolve secret strictly from options.secret by default.
    // Client-supplied secret is only accepted if allowClientSecret is explicitly enabled.
    let secret: string | null | undefined = null;
    if (this.options.allowClientSecret && credentials.secret) {
      secret = credentials.secret;
    } else if (this.options.secret) {
      if (typeof this.options.secret === "function") {
        secret = await this.options.secret(account.trim());
      } else {
        secret = this.options.secret;
      }
    }

    if (!secret || typeof secret !== "string" || secret.trim().length === 0) {
      throw new EasyAuthError(
        "INVALID_CREDENTIALS",
        `No authoritative TOTP secret found for account "${account}". Configure options.secret or pass secret with allowClientSecret enabled.`
      );
    }

    const verification = TotpProvider.verifyTokenWithCounter(secret, code.trim(), {
      step: this.step,
      window: this.window,
      digits: this.digits,
    });

    if (!verification.valid || verification.counter === undefined) {
      if (maxFailed > 0) {
        const lock = this.failedAttempts.get(normalizedAccount) || { count: 0, lockedUntil: 0 };
        lock.count += 1;
        if (lock.count >= maxFailed) {
          lock.lockedUntil = Date.now() + lockoutMs;
        }
        this.failedAttempts.set(normalizedAccount, lock);
      }
      throw new EasyAuthError(
        "INVALID_CREDENTIALS",
        "Invalid or expired 6-digit Google OTP code."
      );
    }

    // Reset failed attempts on success
    if (maxFailed > 0) {
      this.failedAttempts.delete(normalizedAccount);
    }

    const counter = verification.counter;

    // 🔒 Replay defense (RFC 6238 Section 5.2): Enforce monotonic time-step counter
    if (this.options.enforceMonotonicCounter !== false) {
      const lastCounter = this.lastUsedTimeSteps.get(normalizedAccount);
      if (lastCounter !== undefined && counter <= lastCounter) {
        throw new EasyAuthError(
          "INVALID_CREDENTIALS",
          "TOTP code has already been used. Please wait for the next time-step."
        );
      }
      this.lastUsedTimeSteps.set(normalizedAccount, counter);

      // Safe pruning: Only prune oldest excess entries (FIFO/LRU), never wipe all active replay counters!
      if (this.lastUsedTimeSteps.size > 10000) {
        const excess = this.lastUsedTimeSteps.size - 8000;
        const keys = this.lastUsedTimeSteps.keys();
        for (let i = 0; i < excess; i++) {
          const k = keys.next().value;
          if (k) this.lastUsedTimeSteps.delete(k);
        }
      }
    }

    // Custom hook for distributed consumption (e.g. Redis)
    if (this.options.consumeOtp) {
      const consumed = await this.options.consumeOtp(normalizedAccount, code.trim(), counter);
      if (!consumed) {
        throw new EasyAuthError(
          "INVALID_CREDENTIALS",
          "TOTP code has already been consumed or rejected by replay check."
        );
      }
    }

    return {
      providerUserId: normalizedAccount,
      profile: {
        account: account.trim(),
      },
    };
  }
}

/**
 * Convenient alias for Google Authenticator OTP
 */
export { TotpProvider as GoogleOtpProvider };
